image: rust:latest

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

cache:
  paths:
    - .cargo
    - build

stages: 
  - build

before_script:
  - rustc --version && cargo --version
  - apt-get update -qq && apt-get install -yqq clang upx python3-pip --no-install-recommends
  - cargo install pyoxidizer
  - export PATH="$CI_PROJECT_DIR/.cargo/bin:$PATH"

release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - make build
    - pip3 install -U gitlab-release
    - gitlab-release --link-artifact ./build/x86_64-unknown-linux-gnu/release/install/qbittools
  artifacts:
    paths:
      - ./build/x86_64-unknown-linux-gnu/release/install/qbittools
  only:
    - tags
