image: python:3.6-stretch
stages: 
  - build

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make deps

release:
  stage: build
  script:
    - make build
    - pip3 install gitlab-release
    - gitlab-release --link-artifact dist/qbitools
  artifacts:
    paths:
      - dist/qbitools
  only:
    - tags