image: python:3.7-stretch

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CCACHE_BASEDIR: "$PWD"
  CCACHE_DIR: "$PWD/ccache"

cache:
  paths:
    - .cache/pip
    - venv/
    - ccache

stages: 
  - build

before_script:
  - apt-get update -qq && apt-get install -yqq ccache
  - ccache --zero-stats || true
  - ccache --show-stats || true
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make deps

after_script:
  - ccache --show-stats

release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - make build
    - make package
    - pip3 install -U gitlab-release
    - gitlab-release --link-artifact qbittools
  artifacts:
    paths:
      - qbittools
  only:
    - tags
