image: python:3

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYOXIDIZER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pyoxidizer"

cache:
  paths:
    - .cache
    - .cargo
    - venv

stages: 
  - build

before_script:
  - apt-get update -qq && apt-get install -yqq clang upx binutils musl-tools --no-install-recommends
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
  - export PATH="$CI_PROJECT_DIR/.cargo/bin:$PATH"
  - rustc --version && cargo --version
  - rustup target add x86_64-unknown-linux-musl
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pyoxidizer==0.15.0
 
release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - pyoxidizer build --release --target-triple x86_64-unknown-linux-musl
    - strip build/x86_64-unknown-linux-musl/release/install/qbittools
    - upx --best --lzma build/x86_64-unknown-linux-musl/release/install/qbittools
    - cp ./build/x86_64-unknown-linux-musl/release/install/qbittools ./qbittools
    - pip install -U gitlab-release
    - gitlab-release --link-artifact qbittools
  artifacts:
    paths:
      - qbittools
  only:
    - tags
