image: python:3

variables:
  

cache:
  paths:
    - .cache
    - venv
    - build
    - .cargo

stages: 
  - build

before_script:

release:
  stage: build
  script:
    
    - pip install -U gitlab-release
    - gitlab-release qbittools_linux_x86_64
  artifacts:
    paths:
      - qbittools_linux_x86_64
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
