image: rust:latest

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

cache:
  paths:
    - .cargo

stages: 
  - build

before_script:
  - rustc --version && cargo --version
  - apt-get update -qq && apt-get install -yqq clang
  - cargo install pyoxidizer

release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - make build
    - pip3 install -U gitlab-release
    - gitlab-release --link-artifact ./build/x86_64-unknown-linux-gnu/release/install/qbittools
  artifacts:
    paths:
      - qbittools
  only:
    - tags
