image: docker:20
variables:
  REGISTRY_IMAGE_NAME: "registry.gitlab.com/alexkm/qbittools"
  CACHE_IMAGE_NAME: "registry.gitlab.com/alexkm/qbittools:cache"
  BUILDKIT_INLINE_CACHE: "1"
#cache:
#  paths:
#    - cache
services:
  - docker:20-dind

stages:
  - build

before_script:
   - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
   - docker context create builder-context
   - docker buildx create --name builderx --driver docker-container --use builder-context
   - apk add --no-cache python3 py3-pip git

build_binary_amd64:
  stage: build
  script:
    - pip3 --version && python3 --version
    - pip3 install gitlab-release
    - mkdir -p ./cache
    - docker buildx build --platform=linux/amd64 -f Dockerfile.pyoxidizer --build-arg TARGET=x86_64-unknown-linux-musl --build-arg VERSION=$CI_COMMIT_TAG --build-arg CACHE_DIR=linux_amd64 --build-arg RUSTC_WRAPPER="" -o out/linux_amd64 .
    - rm -rf ./cache/linux_amd64
#    - mv out/linux_amd64/cache ./cache/linux_amd64
    - mv out/linux_amd64/qbittools qbittools_linux_x86_64
    - gitlab-release qbittools_linux_x86_64
  artifacts:
    paths:
      - qbittools_linux_x86_64
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

build_docker:
  stage: build
  script:
    - docker buildx build --cache-from "$REGISTRY_IMAGE_NAME:latest" -t "$REGISTRY_IMAGE_NAME:$CI_COMMIT_TAG" --platform=linux/amd64,linux/arm64 .
    - docker tag "$REGISTRY_IMAGE_NAME:$CI_COMMIT_TAG" "$REGISTRY_IMAGE_NAME:latest"
	  - docker push "$REGISTRY_IMAGE_NAME:$CI_COMMIT_TAG"
	  - docker push "$REGISTRY_IMAGE_NAME:latest"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

# maybe when pyoxidizer will work with arm64 musl linux builds
# build_arm64:
#     stage: build
#     script:
#       - docker buildx build --cache-from "$CACHE_IMAGE_NAME" --tag "$CACHE_IMAGE_NAME"  --push --platform=linux/arm64/v8 .
