image: python:latest
stages: 
  - build

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make deps

release:
  stage: build
  script:
    - make build
    - pip3 install gitlab-release
    - gitlab-release dist/qbitools
  only:
    - tags
