image: python:3.7-stretch

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages: 
  - build

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make deps

release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - make build
    - make package
    - pip3 install gitlab-release
    - gitlab-release --link-artifact qbittools
  artifacts:
    paths:
      - qbittools
  only:
    - tags
