image: python:3

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYOXIDIZER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pyoxidizer"
  TARGET: "x86_64-unknown-linux-musl"
  SCCACHE_IDLE_TIMEOUT: "0"
  SCCACHE_DIR: "$CI_PROJECT_DIR/.cache/sccache"
  RUSTC_WRAPPER: "$CI_PROJECT_DIR/sccache"

cache:
  paths:
    - .cache
    - venv
    - build
    - .cargo

stages: 
  - build

before_script:
  - apt-get update -qq && apt-get install -yqq upx binutils musl-tools --no-install-recommends
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pyoxidizer
  - wget -O sccache.tar.gz --progress dot:mega https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz
  - tar -xvzf sccache.tar.gz
  - mv sccache-*/sccache $RUSTC_WRAPPER
  - chmod +x $RUSTC_WRAPPER
  - $RUSTC_WRAPPER --start-server
  - $RUSTC_WRAPPER --show-stats
 
release:
  stage: build
  script:
    - echo __version__ = \"$CI_COMMIT_TAG\" > _version.py
    - pyoxidizer build --release --target-triple $TARGET
    - $RUSTC_WRAPPER --show-stats
    - $RUSTC_WRAPPER --stop-server
    - strip build/$TARGET/release/install/qbittools
    - upx --best --lzma build/$TARGET/release/install/qbittools
    - mv ./build/$TARGET/release/install/qbittools ./qbittools_linux_x86_64
    - pip install -U gitlab-release
    - gitlab-release qbittools_linux_x86_64
  artifacts:
    paths:
      - qbittools_linux_x86_64
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
