image: python:3
stages: 
  - run

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run:
  stage: run
  script:
    - make all
    - pip3 install gitlab-release
    - gitlab-release dist/qbitools
  only:
    - tags
