stages:
  - build
  - deploy

build:
  stage: build
  image: python:3
  script:
    - make all

release:
  stage: deploy
  image: python:3
  script:
    - pip3 install gitlab-release
    - gitlab-release dist/qbitools
  only:
    - tags
